### PR TITLE
Added Step-by-step Instructions In Readme

### PR DESCRIPTION
**Pull request by prathamesh-borse**
@harikanani @adityamangal1  
Can u please review this Pull Request?
#22 This Pull Request is simplifying this issue.

### CODE REVIEW

**Review by harikanani — APPROVED** [review]

**Comment by adityamangal1** [comment]
Great work @prathamesh-borse

**Comment by prathamesh-borse** [comment]
Thanks, Man @adityamangal1.!
Can u please let me know what else I can improve in this repository?

**Comment by harikanani** [comment]
@prathamesh-borse you can create page for hacktoberfest checkout issue #11

**Comment by prathamesh-borse** [comment]
> @prathamesh-borse you can create a page for hacktoberfest checkout issue #11

OK, So I can get ahead with that issue But I want clear clarity on what exactly I have to add to the Hacktoberfest Page.

**Pull request merged**
